
# enable app support
APP=1
APP_STACKSIZE=300

VPATH += src/
PROJ_OBJ += app.o
PROJ_OBJ += wallfollowing_multiranger_onboard.o
PROJ_OBJ += lowLevelCommands.o
PROJ_OBJ += stateMachine.o
PROJ_OBJ += SGBA.o
PROJ_OBJ += sensorsUnit.o
PROJ_OBJ += batteryUnit.o


CRAZYFLIE_BASE=../crazyflie-firmware
include $(CRAZYFLIE_BASE)/Makefile